export const en = {
  meta: {
    title: "VibeVideo — AI Video Generation Studio",
    description:
      "Turn your imagination into stunning video with VibeVideo's AI-powered creation studio.",
  },

  nav: {
    home: "Home",
    generate: "Generate",
    library: "Library",
    inspiration: "Inspiration",
    startCreating: "Start Creating",
    pricing: "Pricing",
    login: "Log in",
    signOut: "Sign out",
    profile: "Profile",
    menu: "Menu",
  },

  profile: {
    title: "Profile",
    subtitle: "Manage your account, appearance and language preferences.",
    account: "Account",
    notLoggedIn: "Not signed in",
    loginHint: "Sign in to manage your account settings.",
    goLogin: "Go to login",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    language: "Language",
    signOut: "Sign out",
    signOutConfirm: "Are you sure you want to sign out?",
  },

  theme: {
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    accentColor: "Accent color",
    graphite: "Graphite",
    ocean: "Ocean",
    ember: "Ember",
    forest: "Forest",
  },

  auth: {
    title: "Welcome back",
    subtitle: "Log in to start creating stunning videos with VibeVideo.",
    username: "Username",
    usernamePlaceholder: "Enter your username",
    password: "Password",
    passwordPlaceholder: "Enter your password",
    submit: "Log in",
    submitting: "Logging in...",
    noAccount: "Don't have an account?",
    signUpHint: "Default test account: admin / admin_123",
    backHome: "Back to home",
    showPassword: "Show password",
    hidePassword: "Hide password",
    errorUsernameRequired: "Please enter your username.",
    errorPasswordRequired: "Please enter your password.",
    errorLogin: "Login failed. Please try again.",
    welcome: "Signed in",
    logoutHint: "You've been signed out.",
  },

  footer: {
    tagline:
      "Turn your imagination into stunning video. AI-powered creation for creators, marketers and storytellers everywhere.",
    product: "Product",
    aiGenerator: "AI Generator",
    library: "Library",
    features: "Features",
    company: "Company",
    about: "About",
    blog: "Blog",
    contact: "Contact",
    copyright: "© 2026 VibeVideo. All rights reserved.",
    privacy: "Privacy",
    terms: "Terms",
  },

  hero: {
    badge: "Introducing AI Video Generation 2.0",
    titlePrefix: "Turn your ideas into",
    titleHighlight: "breathtaking video",
    subtitle:
      "Just type what you imagine and get a cinematic, studio-quality video in seconds. No cameras, no software, no experience needed.",
    startGenerating: "Start Generating",
    browseGallery: "Browse Gallery",
    stat4k: "Ultra output",
    stat10s: "Avg. render",
    stat4: "Art styles",
    statInf: "Possibilities",
    trustedBy: "Trusted by creators, marketers and studios worldwide",
    rating: "4.8",
    reviewCount: "1,284 reviews",
    logosLabel: "Loved by teams at",
    noCard: "No credit card required",
    freeForever: "Free forever plan",
    previewAlt: "Cinematic film still generated by VibeVideo",
  },

  steps: {
    badge: "How it works",
    titlePrefix: "From prompt to",
    titleHighlight: "premiere-ready",
    subtitle:
      "Three simple steps separate your idea from a studio-quality video.",
    step1Title: "Describe your scene",
    step1Desc:
      "Type a simple prompt — a mood, a character, a place. VibeVideo understands natural language, not technical settings.",
    step2Title: "Pick a style & render",
    step2Desc:
      "Choose from four art styles and your target aspect ratio, then let the AI render a cinematic clip in seconds.",
    step3Title: "Refine & download",
    step3Desc:
      "Iterate until it's perfect, then export in up to 4K — ready for every platform and every audience.",
  },

  showcase: {
    badge: "Why VibeVideo",
    titlePrefix: "A private model, built for",
    titleHighlight: "your creative flow",
    subtitle:
      "Unlike generic tools, VibeVideo runs on a private generation model tuned for cinematic quality and personal style — so every render feels unmistakably yours.",
    point1Title: "Private generation model",
    point1Desc:
      "Your prompts and renders stay yours. A dedicated model keeps your work private and consistent.",
    point2Title: "Personalized style memory",
    point2Desc:
      "VibeVideo learns your taste over time, so every new render matches the aesthetic you love.",
    point3Title: "Cinematic by default",
    point3Desc:
      "Studio-grade lighting, framing and motion — no post-production skills required.",
    visualAlt: "Filmmaking camera and production equipment",
  },

  testimonials: {
    badge: "Loved by creators",
    titlePrefix: "What our users",
    titleHighlight: "are saying",
    subtitle:
      "Join 300,000+ creators who turn ideas into video every day.",
  },

  features: {
    titlePrefix: "Everything you need to",
    titleHighlight: "create",
    subtitle:
      "A complete AI video studio built for speed, quality and creative freedom.",
    textToVideo: "Text-to-Video",
    textToVideoDesc:
      "Type a simple prompt and watch it become a fully animated scene with natural motion and cinematic framing.",
    fourArtStyles: "Four Art Styles",
    fourArtStylesDesc:
      "Switch between cinematic, anime, realistic and abstract looks to match the exact mood of your story.",
    crystalClear: "Crystal-Clear Output",
    crystalClearDesc:
      "Render in stunning 4K resolution with multiple aspect ratios for every platform — from reels to widescreen.",
    lightningFast: "Lightning Fast",
    lightningFastDesc:
      "Generate polished clips in seconds and iterate instantly until your vision is exactly right.",
  },

  generate: {
    title: "Create your video",
    subtitle: "Describe your scene, pick a style and let the AI do the rest.",
    describeVideo: "Describe your video",
    placeholder: "A cinematic drone shot of a mountain range at sunrise...",
    tryExample: "Try an example",
    examples: [
      "A lone astronaut walking through a neon-lit rain-soaked city street at night",
      "Golden hour waves crashing against a rocky coastline, slow motion cinematic shot",
      "A cozy cabin in a snow-covered forest with smoke rising from the chimney",
    ],
    artStyle: "Art style",
    aspectRatio: "Aspect ratio",
    duration: "Duration",
    generating: "Generating...",
    regenerate: "Regenerate",
    generateVideo: "Generate Video",
    cancel: "Cancel",
    copied: "Copied",
    published: "Published",
    failed: "Generation failed — please try again.",
    errorEmpty: "Please enter a prompt first.",
    preview: "Preview",
    previewIdle: "Standby",
    previewMonitorLabel: "VIBE · MONITOR",
    previewRenderLabel: "RENDER · {duration}S",
    previewEmpty: "Your video will appear here",
    previewEmptyHint:
      "Describe your scene on the right and hit generate to bring it to life.",
    previewGenerating: "Crafting your scene...",
    developing: "Developing",
    previewDone: "Done",
    previewDoneHint: "Your video is ready to preview and download.",
    previewRegenerateHint: "Refine your prompt and regenerate to iterate.",
    previewFailed: "Something went wrong. Please try again.",
    previewTapToPlay: "Click to play the video",
    share: "Share",
    shareToPlatform: "Share to this platform",
    publish: "Publish",
  },

  styles: {
    cinematic: "Cinematic",
    cinematicDesc: "Dramatic film-like lighting & composition",
    anime: "Anime",
    animeDesc: "Vibrant illustrated motion & cel shading",
    realistic: "Realistic",
    realisticDesc: "Photoreal detail and natural physics",
    abstract: "Abstract",
    abstractDesc: "Surreal shapes, color and flow",
  },

  ratios: {
    widescreen: "16:9 · Widescreen",
    vertical: "9:16 · Vertical",
    square: "1:1 · Square",
  },

  library: {
    title: "Your library",
    subtitle: "Browse, preview and manage all your generated videos.",
    filterAll: "All",
    filterCompleted: "Completed",
    filterGenerating: "Generating",
    emptyTitle: "No videos here yet.",
    emptySubtitle: "Start generating and your creations will appear here.",
    statusCompleted: "Completed",
    statusGenerating: "Generating",
    statusFailed: "Failed",
  },

  works: {
    neonCity: "Neon City Drifter",
    goldenCoast: "Golden Coastline",
    starlitMeadow: "Starlit Meadow",
    winterCabin: "Winter Cabin",
    liquidDreams: "Liquid Dreams",
    mountainAscent: "Mountain Ascent",
    auroraFlow: "Aurora Flow",
    desertMirage: "Desert Mirage",
  },

  inspiration: {
    title: "Get inspired",
    subtitle:
      "Explore stunning videos shared by top creators — every piece includes the prompt behind it, so you can learn and remix.",
    filterAll: "All",
    copyPrompt: "Copy prompt",
    copied: "Copied",
    usePrompt: "Use this prompt",
    promptLabel: "Prompt",
    authorBy: "by",
    likes: "likes",
    like: "like",
  },

  pricing: {
    title: "Simple, transparent pricing",
    subtitle:
      "Start free and upgrade when you need more. No hidden fees, cancel anytime.",
    monthly: "Monthly",
    yearly: "Yearly",
    saveYearly: "Save 20%",
    perMonth: "/mo",
    perYear: "/yr",
    billedMonthly: "Billed monthly",
    billedYearly: "Billed annually",
    currentPlan: "Current plan",
    choosePlan: "Choose plan",
    selected: "Plan selected",
    popular: "Most popular",
    plans: {
      free: "Free",
      freeTagline: "For trying things out",
      pro: "Pro",
      proTagline: "For serious creators",
      studio: "Studio",
      studioTagline: "For teams & agencies",
    },
    ctaFree: "Get started",
    ctaPro: "Upgrade to Pro",
    ctaStudio: "Upgrade to Studio",
    features: {
      freeVideos: "3 videos per month",
      durationFree: "Up to 15s videos",
      watermark: "VibeVideo watermark",
      stdRes: "720p resolution",
      community: "Community support",
      proVideos: "100 videos per month",
      durationPro: "Up to 30s videos",
      noWatermark: "No watermark",
      hdRes: "1080p & 4K output",
      allStyles: "All art styles",
      priority: "Priority rendering",
      unlimitedVideos: "Unlimited videos",
      durationStudio: "Up to 60s videos",
      ultraRes: "4K & upscaling",
      commercial: "Commercial license",
      apiAccess: "API access",
      dedicated: "Dedicated support",
    },
    faqTitle: "Frequently asked questions",
    faqSubtitle: "Everything you need to know about our plans.",
    faq1: "Can I cancel my subscription anytime?",
    faq1a:
      "Yes. You can cancel at any time from your account settings. You'll keep access until the end of your billing period.",
    faq2: "What payment methods do you accept?",
    faq2a:
      "We accept all major credit cards, PayPal, and Apple Pay / Google Pay where available.",
    faq3: "Is there a free trial?",
    faq3a:
      "The Free plan is free forever. Pro and Studio plans include a 14-day money-back guarantee.",
    faq4: "Can I change plans later?",
    faq4a:
      "Absolutely. Upgrade, downgrade, or switch between monthly and yearly billing whenever you like.",
  },
} as const;

// Deeply widen literal types back to `string` so that other locales
// (e.g. zh) can hold arbitrary text while preserving the exact structure.
type Widen<T> = T extends string
  ? string
  : T extends readonly (infer U)[]
    ? readonly Widen<U>[]
    : T extends object
      ? { [K in keyof T]: Widen<T[K]> }
      : T;

export type Translation = Widen<typeof en>;
